
# raspberry pi ver 1.2
FROM ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:main

RUN dpkg --add-architecture armhf
RUN apt update
RUN apt-get install -y crossbuild-essential-armhf wget pkg-config bzip2 make automake libtool
ENV CC=arm-linux-gnueabihf-gcc
RUN wget --no-check-certificate http://www.alsa-project.org/files/pub/lib/alsa-lib-1.2.11.tar.bz2 && tar xf alsa-lib-1.2.11.tar.bz2 \
&& cd alsa-lib-1.2.11 && ./configure --with-pic --host=arm-linux-gnueabihf --prefix=/usr/lib/arm-linux-gnueabihf \
&& make -j$(nproc) && make install

ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/lib/pkgconfig
ENV PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/lib
ENV PKG_CONFIG_SYSROOT_DIR=/
ENV PKG_CONFIG_ALLOW_CROSS=1
