
[target.'cfg(target_env = "musl")']
linker = "clang"
rustflags = ["-C", "target-feature=-crt-static"]

[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-none-linux-gnueabihf-gcc"
